INSERT INTO OWNERS (FIRST_NAME, LAST_NAME,ADDRESS,EMAIL,PHONE_NUMBER) VALUES ('Juan Manuel','Sanchez','Sierra grande #1004','sachez@gmail.com','1233212323');
INSERT INTO OWNERS (FIRST_NAME, LAST_NAME,ADDRESS,EMAIL,PHONE_NUMBER) VALUES ('María','Perez','Venustiano Carranza#5','maria.perez@gmail.com','4421345678');

INSERT INTO SPECIES(NAME) VALUES ('Perro');
INSERT INTO SPECIES(NAME) VALUES ('Gato');
INSERT INTO SPECIES(NAME) VALUES ('Ave');

INSERT INTO MEDICATIONS(NAME,NORMAL_DOSAGE,MAXIMUM_DOSAGE,UNIT_COST) VALUES ('Ketamina','200','500','120');
INSERT INTO MEDICATIONS(NAME,NORMAL_DOSAGE,MAXIMUM_DOSAGE,UNIT_COST) VALUES ('Antimicrobiano','50','80','60');
INSERT INTO MEDICATIONS(NAME,NORMAL_DOSAGE,MAXIMUM_DOSAGE,UNIT_COST) VALUES ('Salmónidos','1','1','300');

INSERT INTO TREATMENTS(NAME) VALUES('Salmonelosis');
INSERT INTO TREATMENTS(NAME) VALUES('Antirrabico');
INSERT INTO TREATMENTS(NAME) VALUES('Salmonelosis');

INSERT INTO PETS(SPECIE_ID,OWNER_ID,NAME,GENDER,COLOR,DATE_OF_BIRTH) VALUES(1,1,'Estella','F','Cafe','2011-10-01');
INSERT INTO PETS(SPECIE_ID,OWNER_ID,NAME,GENDER,COLOR,DATE_OF_BIRTH) VALUES(1,1,'Luna','M','Negro','2011-11-01');
INSERT INTO PETS(SPECIE_ID,OWNER_ID,NAME,GENDER,COLOR,DATE_OF_BIRTH) VALUES(1,1,'Roger','F','Blanco','2011-12-01');
INSERT INTO PETS(SPECIE_ID,OWNER_ID,NAME,GENDER,COLOR,DATE_OF_BIRTH) VALUES(1,2,'Blue','M','Negro','2011-05-01');
INSERT INTO PETS(SPECIE_ID,OWNER_ID,NAME,GENDER,COLOR,DATE_OF_BIRTH) VALUES(1,2,'Pinky','F','Cafe','2011-09-01');


