CREATE TABLE OWNERS(
  OWNER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PHONE_NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE SPECIES(
  SPECIE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100)
);

CREATE TABLE MEDICATIONS(
  MEDICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  NORMAL_DOSAGE DOUBLE,
  MAXIMUM_DOSAGE DOUBLE,
  UNIT_COST DOUBLE
);

CREATE TABLE TREATMENTS(
  TREATMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE TREATMENT_MEDICATION(
  TREATMENT_ID BIGINT NOT NULL,
  MEDICATION_ID BIGINT NOT NULL,
  DOSIS DOUBLE,
  DAYS INT
);

CREATE TABLE VACCINES(
  VACCINE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PETS(
  PET_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SPECIE_ID BIGINT NOT NULL,
  OWNER_ID BIGINT NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  GENDER CHAR(1),
  COLOR VARCHAR(20) NOT NULL,
  DATE_OF_BIRTH DATE
);


CREATE TABLE PET_TREATMENT(
  PET_ID BIGINT NOT NULL,
  TREATMENT_ID BIGINT NOT NULL,
  VISIT_DAY DATE
);


CREATE TABLE MEASUREMENTS(
  PET_ID BIGINT NOT NULL,
  HIGHT DOUBLE NOT NULL,
  WEIGHT DOUBLE,
  VISIT_DAY DATE
);

CREATE TABLE PET_VACCINE(
  PET_ID BIGINT NOT NULL,
  VACCINE_ID BIGINT NOT NULL
 );


ALTER TABLE PET_TREATMENT ADD FOREIGN KEY (PET_ID) REFERENCES PETS(PET_ID);
ALTER TABLE PET_TREATMENT ADD FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS(TREATMENT_ID);
ALTER TABLE TREATMENT_MEDICATION ADD FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATIONS(MEDICATION_ID);
ALTER TABLE TREATMENT_MEDICATION ADD FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENTS(TREATMENT_ID);
ALTER TABLE PETS ADD FOREIGN KEY (OWNER_ID) REFERENCES OWNERS(OWNER_ID);
ALTER TABLE PETS ADD FOREIGN KEY (SPECIE_ID) REFERENCES SPECIES(SPECIE_ID);
ALTER TABLE PET_VACCINE ADD FOREIGN KEY (PET_ID) REFERENCES PETS(PET_ID);
ALTER TABLE PET_VACCINE ADD FOREIGN KEY (VACCINE_ID) REFERENCES VACCINES(VACCINE_ID);



